#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)Makefile	1.2	05/02/16 SMI"
#

TOP = ..

SUBDIRS = dumbreset hypervisor

include $(TOP)/Makefile.master
