#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)Makefile	1.4	05/03/31 SMI"
#

TOP=..

SUBDIRS = mdgen mdlint

include $(TOP)/Makefile.master
